### ISSUE TITLE
Make docker_install configurable by flattening its structure

### ISSUE THREAD

**Issue by gw0** [MVladislav/ansible-docker#1]
### Is your feature request related to a problem? Please describe.

In order to modify anything under the `docker_install` variable (https://github.com/MVladislav/ansible-docker/blob/main/defaults/main.yml#L19-L37) one needs to make a copy of the whole dict and modify what he needs. This is due to an Ansible design decision to not merge dicts (https://stackoverflow.com/a/23855364) and consequently one can not just override a specific value.

### Describe the solution you'd like

It would be easy to configure anything if the `docker_install` variable would be flattened into variables with simple types (e.g. `docker_install_version: stable`).

### Describe alternatives you've considered

/

### Additional context

/

**Comment by MVladislav** [comment]
`docker_install` variable is flatten for each variable as `docker_install_*`, 
to not need copy the whole dict and modify only few needs.

```yml
docker_install_gpg:
  id: 0EBFCD88
  url: https://download.docker.com/linux/ubuntu/gpg
  name: docker_release_ce.gpg
docker_install_repo: https://download.docker.com/linux/ubuntu
docker_install_version: stable
# NOTE: manual update when newer version available
# NOTE: will fallback when current install under lunar
docker_install_release_fallback: jammy
docker_install_release_skip_lunar: lunar
docker_install_apt:
  - docker-ce
  - docker-ce-cli
  - docker-ce-rootless-extras
  - containerd.io
  - docker-compose-plugin
docker_install_pip: []
```
